//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfAddressDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfAddressDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfAddressDto {
    /** Gets or sets the items for the current page. */
    items?: AddressDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents an address summary for API responses. */
export interface AddressDto {
    /** Gets the address identifier. */
    id?: string;
    /** Gets the user identifier. */
    userId?: string;
    /** Gets the address label. */
    label?: string | undefined;
    /** Gets the address type (home, work, etc.). */
    type?: string | undefined;
    /** Gets the first address line. */
    line1?: string | undefined;
    /** Gets the second address line. */
    line2?: string | undefined;
    /** Gets the city. */
    city?: string | undefined;
    /** Gets the state or region. */
    state?: string | undefined;
    /** Gets the postal code. */
    postalCode?: string | undefined;
    /** Gets the country. */
    country?: string | undefined;
    /** Gets whether this address is the default. */
    isDefault?: boolean;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfAddressDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: AddressDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new address. */
export interface CreateAddressCommand {
    /** Gets or sets the user identifier. */
    userId?: string;
    /** Gets or sets the address label. */
    label?: string | undefined;
    /** Gets or sets the address type (home, work, etc.). */
    type?: string | undefined;
    /** Gets or sets the first address line. */
    line1?: string | undefined;
    /** Gets or sets the second address line. */
    line2?: string | undefined;
    /** Gets or sets the city. */
    city?: string | undefined;
    /** Gets or sets the state or region. */
    state?: string | undefined;
    /** Gets or sets the postal code. */
    postalCode?: string | undefined;
    /** Gets or sets the country. */
    country?: string | undefined;
    /** Gets or sets whether this address is the default. */
    isDefault?: boolean;
}

/** Command to update an existing address. */
export interface UpdateAddressCommand {
    /** Gets or sets the address identifier. */
    id?: string;
    /** Gets or sets the address label. */
    label?: string | undefined;
    /** Gets or sets the address type (home, work, etc.). */
    type?: string | undefined;
    /** Gets or sets the first address line. */
    line1?: string | undefined;
    /** Gets or sets the second address line. */
    line2?: string | undefined;
    /** Gets or sets the city. */
    city?: string | undefined;
    /** Gets or sets the state or region. */
    state?: string | undefined;
    /** Gets or sets the postal code. */
    postalCode?: string | undefined;
    /** Gets or sets the country. */
    country?: string | undefined;
    /** Gets or sets whether this address is the default. */
    isDefault?: boolean | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfString {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: string | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfLoginResponse {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: LoginResponse | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents the response returned after a successful login, containing the authentication token and its expiration time. */
export interface LoginResponse {
    token?: string | undefined;
    expiresAt?: Date;
    refreshToken?: string | undefined;
    refreshTokenExpiresAt?: Date;
}

/** Command to authenticate a user. */
export interface LoginCommand {
    /** Gets or sets the username for login. */
    username?: string | undefined;
    /** Gets or sets the email for login. */
    email?: string | undefined;
    /** Gets or sets the password for login. */
    password?: string | undefined;
}

/** Command to register a new user. */
export interface RegisterCommand {
    /** Gets or sets the username for the new user. */
    username?: string | undefined;
    /** Gets or sets the email for the new user. */
    email?: string | undefined;
    /** Gets or sets the password for the new user. */
    password?: string | undefined;
}

/** Command to refresh an access token using a refresh token. */
export interface RefreshTokenCommand {
    /** Gets or sets the refresh token. */
    refreshToken?: string | undefined;
}

/** Command to reset a user's password. */
export interface ResetPasswordCommand {
    /** Gets or sets the email for the user. */
    email?: string | undefined;
    /** Gets or sets the reset token. */
    resetToken?: string | undefined;
    /** Gets or sets the new password. */
    newPassword?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfConsentDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfConsentDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfConsentDto {
    /** Gets or sets the items for the current page. */
    items?: ConsentDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a consent summary for API responses. */
export interface ConsentDto {
    /** Gets the consent identifier. */
    id?: string;
    /** Gets the user identifier. */
    userId?: string;
    /** Gets the consent type. */
    type?: string | undefined;
    /** Gets whether the consent is granted. */
    isGranted?: boolean;
    /** Gets when the consent was granted or revoked in UTC. */
    grantedAt?: string | undefined;
    /** Gets the consent version. */
    version?: string | undefined;
    /** Gets the source of the consent. */
    source?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfConsentDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: ConsentDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new consent. */
export interface CreateConsentCommand {
    /** Gets or sets the user identifier. */
    userId?: string;
    /** Gets or sets the consent type. */
    type?: string | undefined;
    /** Gets or sets whether the consent is granted. */
    isGranted?: boolean;
    /** Gets or sets when the consent was granted or revoked in UTC (yyyy-MM-ddTHH:mm:ssZ). */
    grantedAt?: string | undefined;
    /** Gets or sets the consent version. */
    version?: string | undefined;
    /** Gets or sets the source of the consent. */
    source?: string | undefined;
}

/** Command to update an existing consent. */
export interface UpdateConsentCommand {
    /** Gets or sets the consent identifier. */
    id?: string;
    /** Gets or sets the consent type. */
    type?: string | undefined;
    /** Gets or sets whether the consent is granted. */
    isGranted?: boolean | undefined;
    /** Gets or sets when the consent was granted or revoked in UTC (yyyy-MM-ddTHH:mm:ssZ). */
    grantedAt?: string | undefined;
    /** Gets or sets the consent version. */
    version?: string | undefined;
    /** Gets or sets the source of the consent. */
    source?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfContactMethodDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfContactMethodDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfContactMethodDto {
    /** Gets or sets the items for the current page. */
    items?: ContactMethodDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a contact method summary for API responses. */
export interface ContactMethodDto {
    /** Gets the contact method identifier. */
    id?: string;
    /** Gets the user identifier. */
    userId?: string;
    /** Gets the contact method type. */
    type?: string | undefined;
    /** Gets the contact value (email or phone number). */
    value?: string | undefined;
    /** Gets the normalized contact value for lookup. */
    normalizedValue?: string | undefined;
    /** Gets whether the contact method is verified. */
    isVerified?: boolean;
    /** Gets whether the contact method is the primary one. */
    isPrimary?: boolean;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfContactMethodDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: ContactMethodDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new contact method. */
export interface CreateContactMethodCommand {
    /** Gets or sets the user identifier. */
    userId?: string;
    /** Gets or sets the contact method type. */
    type?: string | undefined;
    /** Gets or sets the contact value (email or phone number). */
    value?: string | undefined;
    /** Gets or sets whether the contact method is verified. */
    isVerified?: boolean;
    /** Gets or sets whether the contact method is the primary one. */
    isPrimary?: boolean;
}

/** Command to update an existing contact method. */
export interface UpdateContactMethodCommand {
    /** Gets or sets the contact method identifier. */
    id?: string;
    /** Gets or sets the contact method type. */
    type?: string | undefined;
    /** Gets or sets the contact value (email or phone number). */
    value?: string | undefined;
    /** Gets or sets whether the contact method is verified. */
    isVerified?: boolean | undefined;
    /** Gets or sets whether the contact method is the primary one. */
    isPrimary?: boolean | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfExternalLinkStartResponse {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: ExternalLinkStartResponse | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents the response for starting an external account link flow. */
export interface ExternalLinkStartResponse {
    /** Gets the authorization URL to redirect the user to. */
    authorizationUrl?: string;
    /** Gets the state value used to correlate the link request. */
    state?: string;
    /** Gets the external provider name for the link. */
    provider?: string;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfExternalLinkDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: ExternalLinkDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a linked external provider for a user. */
export interface ExternalLinkDto {
    /** Gets the external provider name. */
    provider?: string;
    /** Gets the provider-specific subject identifier. */
    subjectId?: string;
    /** Gets the external account email address, if available. */
    email?: string | undefined;
    /** Gets the external account display name, if available. */
    displayName?: string | undefined;
    /** Gets the timestamp when the link was created. */
    linkedAtUtc?: Date;
}

/** Command to complete an external account link flow. */
export interface CompleteExternalLinkCommand {
    /** Gets or sets the external provider name. */
    provider?: string | undefined;
    /** Gets or sets the authorization code from the provider. */
    code?: string | undefined;
    /** Gets or sets the state value returned by the provider. */
    state?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfIReadOnlyCollectionOfExternalLinkDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: ExternalLinkDto[] | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfExternalAccessTokenDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: ExternalAccessTokenDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a short-lived access token response for an external provider. */
export interface ExternalAccessTokenDto {
    /** Gets the access token value. */
    accessToken?: string;
    /** Gets the UTC timestamp when the access token expires. */
    expiresAtUtc?: Date;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfGroupDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfGroupDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfGroupDto {
    /** Gets or sets the items for the current page. */
    items?: GroupDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a group summary for API responses. */
export interface GroupDto {
    /** Gets the group identifier. */
    id?: string;
    /** Gets the group name. */
    name?: string | undefined;
    /** Gets the normalized group name. */
    normalizedName?: string | undefined;
    /** Gets the group description. */
    description?: string | undefined;
    /** Gets the group roles by name. */
    roles?: string[];
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfGroupDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: GroupDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new group. */
export interface CreateGroupCommand {
    /** Gets or sets the group name. */
    name?: string | undefined;
    /** Gets or sets the group description. */
    description?: string | undefined;
}

/** Command to assign a role to a group. */
export interface AssignRoleToGroupCommand {
    /** Gets or sets the group identifier. */
    groupId?: string;
    /** Gets or sets the role identifier. */
    roleId?: string;
}

/** Command to assign a user to a group. */
export interface AssignUserToGroupCommand {
    /** Gets or sets the group identifier. */
    groupId?: string;
    /** Gets or sets the user identifier. */
    userId?: string;
}

/** Command to update an existing group. */
export interface UpdateGroupCommand {
    /** Gets or sets the group identifier. */
    id?: string;
    /** Gets or sets the group name. */
    name?: string | undefined;
    /** Gets or sets the group description. */
    description?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfPermissionDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfPermissionDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfPermissionDto {
    /** Gets or sets the items for the current page. */
    items?: PermissionDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a permission summary for API responses. */
export interface PermissionDto {
    /** Gets the permission identifier. */
    id?: string;
    /** Gets the permission name. */
    name?: string | undefined;
    /** Gets the normalized permission name. */
    normalizedName?: string | undefined;
    /** Gets the permission description. */
    description?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPermissionDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PermissionDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new permission. */
export interface CreatePermissionCommand {
    /** Gets or sets the permission name. */
    name?: string | undefined;
    /** Gets or sets the permission description. */
    description?: string | undefined;
}

/** Command to update an existing permission. */
export interface UpdatePermissionCommand {
    /** Gets or sets the permission identifier. */
    id?: string;
    /** Gets or sets the permission name. */
    name?: string | undefined;
    /** Gets or sets the permission description. */
    description?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfRoleDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfRoleDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfRoleDto {
    /** Gets or sets the items for the current page. */
    items?: RoleDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a role summary for API responses. */
export interface RoleDto {
    id?: string;
    name?: string | undefined;
    normalizedName?: string | undefined;
    description?: string | undefined;
    permissions?: string[];
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfRoleDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: RoleDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new role. */
export interface CreateRoleCommand {
    name?: string | undefined;
    description?: string | undefined;
}

/** Command to update an existing role. */
export interface UpdateRoleCommand {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
}

/** Command to assign a permission to a role. */
export interface AssignPermissionToRoleCommand {
    /** Gets or sets the role identifier. */
    roleId?: string;
    /** Gets or sets the permission identifier. */
    permissionId?: string;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfSessionDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfSessionDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfSessionDto {
    /** Gets or sets the items for the current page. */
    items?: SessionDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a session summary for API responses. */
export interface SessionDto {
    /** Gets the session identifier. */
    id?: string;
    /** Gets the user identifier. */
    userId?: string;
    /** Gets the refresh token for the session. */
    refreshToken?: string | undefined;
    /** Gets the expiration date for the session in UTC. */
    expiresAt?: string | undefined;
    /** Gets the time the session was revoked in UTC. */
    revokedAt?: string | undefined;
    /** Gets the IP address associated with the session. */
    ipAddress?: string | undefined;
    /** Gets the user agent associated with the session. */
    userAgent?: string | undefined;
    /** Gets the device name associated with the session. */
    deviceName?: string | undefined;
    /** Gets whether the session is revoked. */
    isRevoked?: boolean;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfSessionDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: SessionDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new session. */
export interface CreateSessionCommand {
    /** Gets or sets the user identifier. */
    userId?: string;
    /** Gets or sets the refresh token for the session. */
    refreshToken?: string | undefined;
    /** Gets or sets the expiration date for the session in UTC (yyyy-MM-ddTHH:mm:ssZ). */
    expiresAt?: string | undefined;
    /** Gets or sets the revocation time in UTC (yyyy-MM-ddTHH:mm:ssZ). */
    revokedAt?: string | undefined;
    /** Gets or sets the IP address associated with the session. */
    ipAddress?: string | undefined;
    /** Gets or sets the user agent associated with the session. */
    userAgent?: string | undefined;
    /** Gets or sets the device name associated with the session. */
    deviceName?: string | undefined;
}

/** Command to update an existing session. */
export interface UpdateSessionCommand {
    /** Gets or sets the session identifier. */
    id?: string;
    /** Gets or sets the refresh token for the session. */
    refreshToken?: string | undefined;
    /** Gets or sets the expiration date for the session in UTC (yyyy-MM-ddTHH:mm:ssZ). */
    expiresAt?: string | undefined;
    /** Gets or sets the revocation time in UTC (yyyy-MM-ddTHH:mm:ssZ). */
    revokedAt?: string | undefined;
    /** Gets or sets the IP address associated with the session. */
    ipAddress?: string | undefined;
    /** Gets or sets the user agent associated with the session. */
    userAgent?: string | undefined;
    /** Gets or sets the device name associated with the session. */
    deviceName?: string | undefined;
    /** Gets or sets whether the session is revoked. */
    isRevoked?: boolean | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfUserPreferenceDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfUserPreferenceDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfUserPreferenceDto {
    /** Gets or sets the items for the current page. */
    items?: UserPreferenceDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a user preference summary for API responses. */
export interface UserPreferenceDto {
    /** Gets the user preference identifier. */
    id?: string;
    /** Gets the user identifier. */
    userId?: string;
    /** Gets the preference key. */
    key?: string | undefined;
    /** Gets the preference value. */
    value?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfUserPreferenceDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: UserPreferenceDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new user preference. */
export interface CreateUserPreferenceCommand {
    /** Gets or sets the user identifier. */
    userId?: string;
    /** Gets or sets the preference key. */
    key?: string | undefined;
    /** Gets or sets the preference value. */
    value?: string | undefined;
}

/** Command to update an existing user preference. */
export interface UpdateUserPreferenceCommand {
    /** Gets or sets the user preference identifier. */
    id?: string;
    /** Gets or sets the preference key. */
    key?: string | undefined;
    /** Gets or sets the preference value. */
    value?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfUserProfileDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfUserProfileDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfUserProfileDto {
    /** Gets or sets the items for the current page. */
    items?: UserProfileDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a user profile summary for API responses. */
export interface UserProfileDto {
    /** Gets the user profile identifier. */
    id?: string;
    /** Gets the user identifier. */
    userId?: string;
    /** Gets the display name shown to other users. */
    displayName?: string | undefined;
    /** Gets the user's first name. */
    firstName?: string | undefined;
    /** Gets the user's last name. */
    lastName?: string | undefined;
    /** Gets the national identity card number. */
    identityCardNumber?: string | undefined;
    /** Gets the passport number. */
    passportNumber?: string | undefined;
    /** Gets the date of birth in yyyy-MM-dd format. */
    dateOfBirth?: string | undefined;
    /** Gets the place of birth. */
    birthPlace?: string | undefined;
    /** Gets the shoe size. */
    shoeSize?: string | undefined;
    /** Gets the clothing size. */
    clothingSize?: string | undefined;
    /** Gets the waist size. */
    waistSize?: string | undefined;
    /** Gets the profile bio. */
    bio?: string | undefined;
    /** Gets the profile image URL. */
    imageUrl?: string | undefined;
    /** Gets the profile tag. */
    tag?: string | undefined;
    /** Gets the blood type recorded for the user. */
    bloodType?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfUserProfileDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: UserProfileDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new user profile. */
export interface CreateUserProfileCommand {
    /** Gets or sets the user identifier. */
    userId?: string;
    /** Gets or sets the display name shown to other users. */
    displayName?: string | undefined;
    /** Gets or sets the user's first name. */
    firstName?: string | undefined;
    /** Gets or sets the user's last name. */
    lastName?: string | undefined;
    /** Gets or sets the national identity card number. */
    identityCardNumber?: string | undefined;
    /** Gets or sets the passport number. */
    passportNumber?: string | undefined;
    /** Gets or sets the date of birth in yyyy-MM-dd format. */
    dateOfBirth?: string | undefined;
    /** Gets or sets the place of birth. */
    birthPlace?: string | undefined;
    /** Gets or sets the shoe size. */
    shoeSize?: string | undefined;
    /** Gets or sets the clothing size. */
    clothingSize?: string | undefined;
    /** Gets or sets the waist size. */
    waistSize?: string | undefined;
    /** Gets or sets the profile bio. */
    bio?: string | undefined;
    /** Gets or sets the profile image URL. */
    imageUrl?: string | undefined;
    /** Gets or sets the profile tag. */
    tag?: string | undefined;
    /** Gets or sets the blood type recorded for the user. */
    bloodType?: string | undefined;
}

/** Command to update an existing user profile. */
export interface UpdateUserProfileCommand {
    /** Gets or sets the user profile identifier. */
    id?: string;
    /** Gets or sets the display name shown to other users. */
    displayName?: string | undefined;
    /** Gets or sets the user's first name. */
    firstName?: string | undefined;
    /** Gets or sets the user's last name. */
    lastName?: string | undefined;
    /** Gets or sets the national identity card number. */
    identityCardNumber?: string | undefined;
    /** Gets or sets the passport number. */
    passportNumber?: string | undefined;
    /** Gets or sets the date of birth in yyyy-MM-dd format. */
    dateOfBirth?: string | undefined;
    /** Gets or sets the place of birth. */
    birthPlace?: string | undefined;
    /** Gets or sets the shoe size. */
    shoeSize?: string | undefined;
    /** Gets or sets the clothing size. */
    clothingSize?: string | undefined;
    /** Gets or sets the waist size. */
    waistSize?: string | undefined;
    /** Gets or sets the profile bio. */
    bio?: string | undefined;
    /** Gets or sets the profile image URL. */
    imageUrl?: string | undefined;
    /** Gets or sets the profile tag. */
    tag?: string | undefined;
    /** Gets or sets the blood type recorded for the user. */
    bloodType?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfUserDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfUserDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfUserDto {
    /** Gets or sets the items for the current page. */
    items?: UserDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a user summary for API responses. */
export interface UserDto {
    id?: string;
    username?: string | undefined;
    email?: string | undefined;
    phoneNumber?: string | undefined;
    emailConfirm?: boolean;
    phoneNumberConfirm?: boolean;
    twoFactorEnabled?: boolean;
    accessFailedCount?: number;
    isLocked?: boolean;
    isDeleted?: boolean;
    roles?: string[];
    groups?: string[];
    permissions?: string[];
    groupRoles?: { [key: string]: string[]; };
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfUserDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: UserDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new user. */
export interface CreateUserCommand {
    username?: string | undefined;
    email?: string | undefined;
    phoneNumber?: string | undefined;
    password?: string | undefined;
}

/** Command to assign a role to a user. */
export interface AssignRoleToUserCommand {
    /** Gets or sets the user identifier. */
    userId?: string;
    /** Gets or sets the role identifier. */
    roleId?: string;
}

/** Command to update an existing user. */
export interface UpdateUserCommand {
    id?: string;
    username?: string | undefined;
    email?: string | undefined;
    phoneNumber?: string | undefined;
    isLocked?: boolean | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfUserSessionDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: UserSessionDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a user session response containing user context and preferences. */
export interface UserSessionDto {
    /** Gets the user details. */
    user?: UserDto;
    /** Gets the user profile details. */
    profile?: UserProfileDto;
    /** Gets the user preference entries. */
    preferences?: UserPreferenceDto[];
    /** Gets the role names assigned to the user. */
    roles?: string[];
    /** Gets the permission names available to the user. */
    permissions?: string[];
    /** Gets the group names the user belongs to. */
    groups?: string[];
    /** Gets the roles grouped by group name. */
    groupRoles?: { [key: string]: string[]; };
}