//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfLoginResponse {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: LoginResponse | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents the response returned after a successful login, containing the authentication token and its expiration time. */
export interface LoginResponse {
    token?: string | undefined;
    expiresAt?: Date;
    refreshToken?: string | undefined;
    refreshTokenExpiresAt?: Date;
}

/** Command to authenticate a user. */
export interface LoginCommand {
    /** Gets or sets the username for login. */
    username?: string | undefined;
    /** Gets or sets the email for login. */
    email?: string | undefined;
    /** Gets or sets the password for login. */
    password?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfString {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: string | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to register a new user. */
export interface RegisterCommand {
    /** Gets or sets the username for the new user. */
    username?: string | undefined;
    /** Gets or sets the email for the new user. */
    email?: string | undefined;
    /** Gets or sets the password for the new user. */
    password?: string | undefined;
}

/** Command to refresh an access token using a refresh token. */
export interface RefreshTokenCommand {
    /** Gets or sets the refresh token. */
    refreshToken?: string | undefined;
}

/** Command to reset a user's password. */
export interface ResetPasswordCommand {
    /** Gets or sets the email for the user. */
    email?: string | undefined;
    /** Gets or sets the reset token. */
    resetToken?: string | undefined;
    /** Gets or sets the new password. */
    newPassword?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfExternalLinkStartResponse {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: ExternalLinkStartResponse | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents the response for starting an external account link flow. */
export interface ExternalLinkStartResponse {
    /** Gets the authorization URL to redirect the user to. */
    authorizationUrl?: string;
    /** Gets the state value used to correlate the link request. */
    state?: string;
    /** Gets the external provider name for the link. */
    provider?: string;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfExternalLinkDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: ExternalLinkDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a linked external provider for a user. */
export interface ExternalLinkDto {
    /** Gets the external provider name. */
    provider?: string;
    /** Gets the provider-specific subject identifier. */
    subjectId?: string;
    /** Gets the external account email address, if available. */
    email?: string | undefined;
    /** Gets the external account display name, if available. */
    displayName?: string | undefined;
    /** Gets the timestamp when the link was created. */
    linkedAtUtc?: Date;
}

/** Command to complete an external account link flow. */
export interface CompleteExternalLinkCommand {
    /** Gets or sets the external provider name. */
    provider?: string | undefined;
    /** Gets or sets the authorization code from the provider. */
    code?: string | undefined;
    /** Gets or sets the state value returned by the provider. */
    state?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfIReadOnlyCollectionOfExternalLinkDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: ExternalLinkDto[] | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfExternalAccessTokenDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: ExternalAccessTokenDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a short-lived access token response for an external provider. */
export interface ExternalAccessTokenDto {
    /** Gets the access token value. */
    accessToken?: string;
    /** Gets the UTC timestamp when the access token expires. */
    expiresAtUtc?: Date;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfPermissionDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfPermissionDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfPermissionDto {
    /** Gets or sets the items for the current page. */
    items?: PermissionDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a permission summary for API responses. */
export interface PermissionDto {
    /** Gets the permission identifier. */
    id?: string;
    /** Gets the permission name. */
    name?: string | undefined;
    /** Gets the normalized permission name. */
    normalizedName?: string | undefined;
    /** Gets the permission description. */
    description?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPermissionDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PermissionDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new permission. */
export interface CreatePermissionCommand {
    /** Gets or sets the permission name. */
    name?: string | undefined;
    /** Gets or sets the permission description. */
    description?: string | undefined;
}

/** Command to update an existing permission. */
export interface UpdatePermissionCommand {
    /** Gets or sets the permission identifier. */
    id?: string;
    /** Gets or sets the permission name. */
    name?: string | undefined;
    /** Gets or sets the permission description. */
    description?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfRoleDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfRoleDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfRoleDto {
    /** Gets or sets the items for the current page. */
    items?: RoleDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a role summary for API responses. */
export interface RoleDto {
    id?: string;
    name?: string | undefined;
    normalizedName?: string | undefined;
    description?: string | undefined;
    permissions?: string[];
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfRoleDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: RoleDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new role. */
export interface CreateRoleCommand {
    name?: string | undefined;
    description?: string | undefined;
}

/** Command to update an existing role. */
export interface UpdateRoleCommand {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfTodoItemDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfTodoItemDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfTodoItemDto {
    /** Gets or sets the items for the current page. */
    items?: TodoItemDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Data Transfer Object representing a to-do item. */
export interface TodoItemDto {
    /** Gets or sets the unique identifier of the to-do item. */
    id?: number;
    /** Gets or sets the identifier of the to-do list to which this item belongs. */
    listId?: number;
    /** Gets or sets the title of the to-do item. */
    title?: string | undefined;
    /** Gets a value indicating whether the to-do item is completed. */
    done?: boolean;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfTodoItemDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: TodoItemDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

export interface CreateTodoItemCommand {
    /** Gets or sets the title of the to-do item. */
    title?: string | undefined;
    /** Gets or sets the ID of the to-do list to which the item belongs. */
    listId?: number;
}

/** Command to update a todos item. */
export interface UpdateTodoItemComand {
    /** Gets or sets the identifier of the todos item. */
    id?: number;
    /** Gets or sets the new title of the todos item. */
    title?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfObject {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: any | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfTodoListDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfTodoListDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfTodoListDto {
    /** Gets or sets the items for the current page. */
    items?: TodoListDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Data Transfer Object (DTO) for a to-do list, including its items. */
export interface TodoListDto {
    /** Gets the unique identifier of the to-do list. */
    id?: number;
    /** Gets the title of the to-do list. */
    title?: string | undefined;
    /** Gets the color associated with the to-do list. */
    colour?: string | undefined;
    /** Gets the collection of to-do items in the list. */
    items?: TodoItemDto[];
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfTodoListDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: TodoListDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new Todos List. */
export interface CreateTodoListCommand {
    /** Gets or sets the title of the Todos List. */
    title?: string | undefined;
}

/** Command to update a TodoList. */
export interface UpdateTodoListCommand {
    /** Gets or sets the identifier of the TodoList to update. */
    id?: number;
    /** Gets or sets the new title for the TodoList. */
    title?: string | undefined;
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfPaginatedEnumerableOfUserDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: PaginatedEnumerableOfUserDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Represents a paginated collection of items with pagination metadata. */
export interface PaginatedEnumerableOfUserDto {
    /** Gets or sets the items for the current page. */
    items?: UserDto[] | undefined;
    /** Gets or sets the current page number. */
    pageNumber?: number;
    /** Gets or sets the total number of pages. */
    totalPages?: number;
    /** Gets or sets the total number of items. */
    totalCount?: number;
    /** Gets a value indicating whether there is a previous page. */
    hasPreviousPage?: boolean;
    /** Gets a value indicating whether there is a next page. */
    hasNextPage?: boolean;
}

/** Represents a user summary for API responses. */
export interface UserDto {
    id?: string;
    username?: string | undefined;
    email?: string | undefined;
    phoneNumber?: string | undefined;
    emailConfirm?: boolean;
    phoneNumberConfirm?: boolean;
    twoFactorEnabled?: boolean;
    accessFailedCount?: number;
    isLocked?: boolean;
    isDeleted?: boolean;
    roles?: string[];
    groups?: string[];
    permissions?: string[];
    groupRoles?: { [key: string]: string[]; };
}

/** Represents a standard response wrapper for service or API operations. Contains success status, message, data payload, and optional error details. */
export interface BaseResponseOfUserDto {
    /** Gets a value indicating whether the operation was successful. */
    success?: boolean;
    /** Gets an optional message describing the result. */
    message?: string | undefined;
    /** Gets the data payload of the response. */
    data?: UserDto | undefined;
    /** Validation or business errors grouped by field/property name. */
    errors?: { [key: string]: string[]; } | undefined;
}

/** Command to create a new user. */
export interface CreateUserCommand {
    username?: string | undefined;
    email?: string | undefined;
    phoneNumber?: string | undefined;
    password?: string | undefined;
}

/** Command to update an existing user. */
export interface UpdateUserCommand {
    id?: string;
    username?: string | undefined;
    email?: string | undefined;
    phoneNumber?: string | undefined;
    isLocked?: boolean | undefined;
}